import argparse
import json
import os
import sys
from datetime import datetime, timezone


def load_audit_results(input_file):
    """Load the JSON generated by audit_s3.py."""

    if not os.path.isfile(input_file):
        raise FileNotFoundError(
            f"Audit results file does not exist: "
            f"{input_file}"
        )

    with open(
        input_file,
        "r",
        encoding="utf-8",
    ) as file:
        return json.load(file)


def generate_report(data, output_file):
    """Generate a Markdown security report."""

    bucket = data["bucket"]
    generated_at = data["generated_at"]
    results = data["results"]

    passed = sum(
        item["status"] == "PASS"
        for item in results
    )

    failed = sum(
        item["status"] == "FAIL"
        for item in results
    )

    total = len(results)

    if failed == 0:
        overall_status = "PASS"
    else:
        overall_status = "FAIL"

    output_directory = os.path.dirname(
        os.path.abspath(output_file)
    )

    os.makedirs(
        output_directory,
        exist_ok=True,
    )

    with open(
        output_file,
        "w",
        encoding="utf-8",
    ) as report:

        report.write(
            "# S3 Security Audit Report\n\n"
        )

        report.write(
            f"**Bucket:** `{bucket}`\n\n"
        )

        report.write(
            f"**Audit timestamp:** `{generated_at}`\n\n"
        )

        report.write(
            f"**Overall status:** "
            f"**{overall_status}**\n\n"
        )

        report.write("## Summary\n\n")

        report.write(
            f"| Metric | Result |\n"
            f"|---|---:|\n"
            f"| Total checks | {total} |\n"
            f"| Passed | {passed} |\n"
            f"| Failed | {failed} |\n\n"
        )

        report.write(
            "## Security Controls\n\n"
        )

        report.write(
            "| Control | Status | Details |\n"
            "|---|---|---|\n"
        )

        for item in results:

            status = item["status"]

            report.write(
                f"| {item['check']} "
                f"| **{status}** "
                f"| {item['details']} |\n"
            )

        report.write(
            "\n## Failed Controls\n\n"
        )

        failed_controls = [
            item
            for item in results
            if item["status"] == "FAIL"
        ]

        if not failed_controls:
            report.write(
                "No failed security controls were detected.\n"
            )

        else:
            for item in failed_controls:
                report.write(
                    f"- **{item['check']}** — "
                    f"{item['details']}\n"
                )

        report.write(
            "\n## Assessment\n\n"
        )

        if failed == 0:
            report.write(
                "All automated S3 security checks passed.\n"
            )
        else:
            report.write(
                f"{failed} security control(s) failed "
                "and should be investigated.\n"
            )

        report.write(
            "\n---\n\n"
        )

        report.write(
            "Generated automatically by "
            "the Secure Enterprise File Platform.\n"
        )

    print(
        f"Security report generated: {output_file}"
    )


def main():
    parser = argparse.ArgumentParser(
        description="Generate a security report from an S3 audit."
    )

    parser.add_argument(
        "--input",
        default="audit_results.json",
        help="Audit JSON file.",
    )

    parser.add_argument(
        "--output",
        default="reports/security_report.md",
        help="Markdown report output.",
    )

    args = parser.parse_args()

    try:
        data = load_audit_results(
            args.input
        )

        generate_report(
            data,
            args.output,
        )

    except (
        FileNotFoundError,
        json.JSONDecodeError,
        KeyError,
    ) as error:
        print(
            f"Report generation failed: {error}",
            file=sys.stderr,
        )
        sys.exit(1)


if __name__ == "__main__":
    main()